gitHub:
  defaultOwner: 'skypilotcc'
  defaultPublicRepoName: 'toolchain'
  graphQlEndpoint: 'https://api.github.com/graphql'
  restEndpoint: 'https://api.github.com'
  # token: ''  # Set the token in `local/github-tools.yml`
